# spring cloud config server properties
server:
  port: 8888 # default port

spring:
  application:
    name: config-server
  profiles:
    # must set active profile to native
    active: native
  cloud:
    config:
      server:
        native:
          # search locations for config files
          search-locations: file:./config-repo, file:../config-repo, file:../../config-repo
