version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:3.5
    user: "root"
    container_name: docker-deploy-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./docker/zookeeper-data:/bitnami
    networks:
      - docker-deploy

  kafka:
    image: bitnami/kafka:3.0
    user: "root"
    container_name: docker-deploy-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://docker-deploy-kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=docker-deploy-zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./docker/kafka-data:/bitnami
    networks:
      - docker-deploy

  redis:
    image: redis:6.2
    container_name: docker-deploy-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis-data:/data
    networks:
      - docker-deploy

  mysql:
    image: mysql:8.0
    container_name: docker-deploy-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_AUTH_PLUGIN=caching_sha2_password
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/exchange-schema.sql:ro
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql-data:/var/lib/mysql
    networks:
      - docker-deploy

  config:
    container_name: config-server
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mysql
      - redis
      - kafka
      - zookeeper
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE=file:../../config-repo
    volumes:
      - ../../config-repo:/config-repo
    networks:
      - docker-deploy

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SERVER=http://config-server:8888
    networks:
      - docker-deploy

  push:
    container_name: push
    build:
      context: ./push
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    environment:
      - CONFIG_SERVER=http://config-server:8888
      - spring.redis.standalone.host=docker-deploy-redis
    networks:
      - docker-deploy

  quotation:
    container_name: quotation
    build:
      context: ./quotation
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      - CONFIG_SERVER=http://config-server:8888
    networks:
      - docker-deploy

  trading-api:
    container_name: trading-api
    build:
      context: ./trading-api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - CONFIG_SERVER=http://config-server:8888
    networks:
      - docker-deploy
      
  trading-engine:
    container_name: trading-engine
    build:
      context: ./trading-engine
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - CONFIG_SERVER=http://config-server:8888
    networks:
      - docker-deploy

  trading-sequencer:
    container_name: trading-sequencer
    build:
      context: ./trading-sequencer
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - CONFIG_SERVER=http://config-server:8888
    networks:
      - docker-deploy

  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CONFIG_SERVER=http://config-server:8888
    networks:
      - docker-deploy

networks:
  docker-deploy:
    driver: bridge