# global configurations

server:
  tomcat:
    use-forward-headers: ${TOMCAT_USE_FORWARD_HEADERS:true}
    protocol-header: ${TOMCAT_PROTOCOL_HEADER:x-forwarded-proto}

exchange:
  config:
    order-book-depth: ${ORDER_BOOK_DEPTH:50}
    debug-mode: ${EXCHANGE_DEBUG_MODE:false}
    time-zone: ${EXCHANGE_TIME_ZONE:}
    hmac-key: ${EXCHANGE_HMAC_KEY:ChangeThisHmacKey4ExchangeConfig}
    session-timeout: ${EXCHANGE_SESSION_TIMEOUT:P3D}
    api-endpoints:
      trading-api: ${TRADING_API:http://trading-api:8001}
      trading-engine-api: ${TRADING_ENGINE_API:http://trading-engine:8002}

  risk-control:
    notify-message-expires: ${NOTIFY_MESSAGE_EXPIRES:PT60S}
    transfer-out-message-expires: ${TRANSFER_OUT_MESSAGE_EXPIRES:P7D}

  setting:
    scheduler:
      cron:
        reload-trading-metadata: ${CRON_RELOAD_TRADING_METADATA:0 */10 * * * *}
        update-latest-price: ${CRON_UPDATE_LATEST_PRICE:0,10,20,30,40,50 * * * * *}
      fixed-delay:
        flush-orderbook: ${FIXED_DELAY_FLUSH_ORDERBOOK:500}
        reinvoke-transfer: ${FIXED_DELAY_REINVOKE_TRANSFER:60000}
        reload-trading-metadata: ${FIXED_DELAY_RELOAD_TRADING_METADATA:600000}
        save-sequence-id: ${FIXED_DELAY_SAVE_SEQUENCE_ID:60000}
    timezone: ${EXCHANGE_TIMEZONE:}
    aes-key: ${EXCHANGE_AES_KEY:CryptoExchangeAESRandomSecureKey}
    endpoint:
      ui: ${UI_ENDPOINT:http://ui:8000}
      meta-api: ${META_API_ENDPOINT:http://trading-api:8001}
      wallet-api: ${WALLET_API_ENDPOINT:http://config-server:8901}
      spots-api: ${SPOTS_API_ENDPOINT:http://config-server:8101}
      spots-trading-internal-api: ${SPOTS_TRADING_INTERNAL_API_ENDPOINT:http://config-server:8103}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:http://trading-kafka:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:}
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:latest}
      max-poll-records: ${KAFKA_CONSUMER_MAX_POLL_RECORDS:500}
      max-partition-fetch-bytes: ${KAFKA_MAX_PARTITION_FETCH_BYTES:1000000}

  redis:
    host: ${REDIS_HOST:trading-redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}

  datasource:
    url: jdbc:mysql://${DB_HOST:trading-mysql}/${DB_NAME:exchange}?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: ${DB_TIMEOUT:3000}
      validation-timeout: ${DB_TIMEOUT:3000}
      max-lifetime: 600000
      maximum-pool-size: ${DB_POOL_MAX:500}
      minimum-idle: ${DB_POOL_IDEL:1}

logging:
  level:
    root: ${LOGGING_ROOT_LEVEL:INFO}
    org.apache.kafka: ${LOGGING_KAFKA_LEVEL:WARN}
    com.helltractor.exchange: ${LOGGING_EXCHANGE_LEVEL:INFO}